### ISSUE TITLE
Can't run 1.0.3 on Minecraft 1.20.1

### ISSUE THREAD

**Issue by MCRusher** [1bacon/drops-into-shulker#1]
I'll just update my minecraft version, but I figured I should mention this since the modrinth page says it supports 1.20-1.20.1

Thanks for the mod.

---

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Drops into Shulker' (drops-into-shulker) 1.0.3 with any version that is compatible with:
		 - minecraft 1.20
Unmet dependency listing:
	 - Mod 'Drops into Shulker' (drops-into-shulker) 1.0.3 requires any version between 1.20.1 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by 1bacon** [comment]
Thanks for the report. 

I over-specified the versions.

```json5
"depends": {
    "fabricloader": ">=0.14.14",
    "minecraft": "~1.20.1",
// should have been `>=1.19-` because nothing really changed anyway
    "java": ">=17"
  },
```

Should be fixed now.

**Comment by MCRusher** [comment]
Yup works fine now, thanks.
