### ISSUE TITLE
quits server when picking up item

### ISSUE THREAD

**Issue by KryptoLMS** [1bacon/drops-into-shulker#5]
the mod quits the server when picking up items with the shulker in off-hand, and keeps quitting when i join the server until the item despawns

**Comment by 1bacon** [comment]
Hey there, thanks for the report.
Can you provide the versions of both the mod loader and the mod, as well as the log of the server.

Is there any output or error message?

**Comment by KryptoLMS** [comment]
fabric-loader-0.16.2-1.21
drops-into-shulker-1.3.2

[14:47:30] [Server thread/INFO]: KryptoLMS joined the game
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:rhombus'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:stripe_bottom'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:stripe_center'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:border'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:stripe_middle'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:half_horizontal'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:circle'
[14:47:33] [Server thread/WARN]: Unable to find banner pattern with id: 'minecraft:border'
[14:48:12] [Server thread/WARN]: Failed to handle packet for /62.107.232.58:54348
net.minecraft.class_148: Ticking player
at net.minecraft.class_3222.method_14226(class_3222.java:652) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_18784(class_3244.java:268) ~[server-intermediary.jar:?]
at net.minecraft.class_2535.method_10754(class_2535.java:401) ~[server-intermediary.jar:?]
at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
at java.base/java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because "$$0" is null
at net.minecraft.class_2591.method_20526(class_2591.java:106) ~[server-intermediary.jar:?]
at net.minecraft.class_2586.handler$zok000$lithium$initSupportCache(class_2586.java:2525) ~[server-intermediary.jar:?]
at net.minecraft.class_2586.<init>(class_2586.java:52) ~[server-intermediary.jar:?]
at net.minecraft.class_2624.<init>(class_2624.java:33) ~[server-intermediary.jar:?]
at net.minecraft.class_2621.<init>(class_2621.java:25) ~[server-intermediary.jar:?]
at net.minecraft.class_2627.<init>(class_2627.java:58) ~[server-intermediary.jar:?]
at net.minecraft.class_2480.method_10123(class_2480.java:94) ~[server-intermediary.jar:?]
at net.minecraft.class_1661.handler$zze000$drops-into-shulker$insertStack(class_1661.java:688) ~[server-intermediary.jar:?]
at net.minecraft.class_1661.method_7394(class_1661.java) ~[server-intermediary.jar:?]
at net.minecraft.class_1542.method_5694(class_1542.java:385) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_7341(class_1657.java:654) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_6007(class_1657.java:627) ~[server-intermediary.jar:?]
at net.minecraft.class_1309.method_5773(class_1309.java:2507) ~[server-intermediary.jar:?]
at net.minecraft.class_1657.method_5773(class_1657.java:312) ~[server-intermediary.jar:?]
at net.minecraft.class_3222.method_14226(class_3222.java:588) ~[server-intermediary.jar:?]
... 9 more
[14:48:12] [Server thread/INFO]: KryptoLMS lost connection: Internal server error
[14:48:12] [Server thread/INFO]: KryptoLMS left the game

**Comment by 1bacon** [comment]
This is weird. I can't reproduce anything similar. What other mods are you using?
Is there a specific setup where it crashes, or does it happen all the time?

**Comment by KryptoLMS** [comment]
quite a lot of other mods, 
![Screenshot 2024-09-14 153409](https://github.com/user-attachments/assets/2d1422cd-38c6-4f62-b346-f0883084cfb1)

but it happens with just these too:
![image](https://github.com/user-attachments/assets/52a22880-f7f5-4743-8f82-7ad4f74af19a)

**Comment by KryptoLMS** [comment]
it happens all the time

**Comment by KryptoLMS** [comment]
do i need to have it installed on both server and client?

**Comment by 1bacon** [comment]
This mod is fully server sided. Are these the server mods? 
There are a lot of client mods in there, only the server is relevant for this crash.

**Comment by KryptoLMS** [comment]
oh right, 
![Screenshot 2024-09-14 160518](https://github.com/user-attachments/assets/96132bd5-8bbf-43cc-b7b1-3d270710b052)
these are the server side mods

**Comment by Loggy98** [comment]
I think this is caused by Lithium. I use this mod in Single Player, and the crash only happens with Lithium enabled. The crash log also shows:

at net.minecraft.class_2586.handler$cgo000$lithium$initSupportCache(class_2586.java:3025) ~[client-intermediary.jar:?]

**Comment by Loggy98** [comment]
I think this is caused by Lithium. I use this mod in Single Player, and the crash only happens with Lithium enabled. The crash log also mentions Lithium:

at net.minecraft.class_2586.handler$cgo000$lithium$initSupportCache(class_2586.java:3025) ~[client-intermediary.jar:?]

**Comment by 1bacon** [comment]
I saw that as well, but had hoped that lithium only shows up because it's optimizations are so prevalent.

But this is most likely still a bug, I use lithium without any problems. You can try to update the mod loader and the lithium version and see if that helps. 
These are the mods that work for me I:
```
drops-into-shulker-1.3.2.jar
fabric-api-0.100.4+1.21.jar
lithium-fabric-mc1.21-0.12.7.jar
```

I'm currently finishing my university degree and cannot spare much time investigating this bug. If you find anything feel free to comment.

**Comment by KryptoLMS** [comment]
it worked

> I saw that as well, but had hoped that lithium only shows up because it's optimizations are so prevalent.
> 
> But this is most likely still a bug, I use lithium without any problems. You can try to update the mod loader and the lithium version and see if that helps. These are the mods that work for me I:
> 
> ```
> drops-into-shulker-1.3.2.jar
> fabric-api-0.100.4+1.21.jar
> lithium-fabric-mc1.21-0.12.7.jar
> ```
> 
> I'm currently finishing my university degree and cannot spare much time investigating this bug. If you find anything feel free to comment.

it worked by downgrading my lithium version to mc1.21-0.12.7.jar, thank you so much! :) <3
